### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by TrojanHorseForSale** [goto-bus-stop/drs-extract#3]
How do I use this tool to extract from a DRS file, its a bit confusing?

**Comment by goto-bus-stop** [comment]
It's a command-line tool, if you have Node.js installed, you can do `npx drs-extract ./input.drs ./output` to extract a file named `input.drs` into a directory named `output`.
Note that the project is quite old so if definitive edition or AoE4 still ship with DRS files, they may not be supported.
